### ISSUE TITLE
Add google+ to social icons

### ISSUE THREAD

**Issue by renich** [theNewDynamic/gohugo-theme-ananke#102]
Please!

**Comment by LimitedEdition1** [comment]
G+ and other icons can be done with iconmonstr.  https://iconmonstr.com/ 
You can generate your own svg icon files.  Search for the icon name, choose the SVG option, and choose the EMBED button and copy what you need to a new file. Or copy an existing social.svg file from the theme  and edit to replace the path info.  

To get the new icon(s) to work:
1. Make a  /layouts/partials folder and copy the theme social-follow.html and modify as needed. 
2. Make a /layouts/partials/svg folder and copy the newly generated svg file(s) to this folder. 
3. Make a /static/css folder and copy the theme social-icons.css file and modify as needed. 
4. Edit the config.toml file and add to the [params] section:
custom_css = ["/css/yourFileName-social-icons.css"]

I ended up redoing all the existing social icons because iconmaster made the path size slightly different than the default theme icons, which caused a very minor height issue,  

Hope this helps. Maybe there's an easier way that others could share as well.

**Comment by budparr** [comment]
Hey, @LimitedEdition1 That's very helpful. I'd love to do a wider set of icons, it's usually a pain to get them consistent.  I'll check this out. It might just be the thing we need.

**Comment by jhenstridge** [comment]
Might it be possible to refactor the social icons as a Hugo menu?  That might make it easier to add new icons or reorder the existing ones.

**Comment by regisphilibert** [comment]
I don't think we need Google+ anymore...
