### ISSUE TITLE
Grouping the articles under Article section

### ISSUE THREAD

**Issue by Omar-Safwat** [theNewDynamic/gohugo-theme-ananke#439]
Hello, though was able to edit the website's content, I would also like to make a few additions, but I can't since I don't fully understand how it all works.

I renamed the **Articles** section to **Projects**. 

What I want to do is add the 3 buttons in red boxes, which are categories, in the image below. When the visitor clicks on one of them, the projects underneath are updated for each of them.
![projects](https://user-images.githubusercontent.com/73256703/138411666-1ee64824-a8ce-4d96-baff-da56c9cb200b.png)

Thank you in advance.

**Comment by budparr** [comment]
Hi @Omar-Safwat You would need to copy the template into your local layouts folder and overwrite it to include the buttons. I imagine your best bet would be to use a taxonomy. For more in depth help you can ask in the Hugo forums because that's really a more general Hugo issue rather than anything specific to this theme.
