### ISSUE TITLE
site-header.html featured image

### ISSUE THREAD

**Issue by tlindsay42** [theNewDynamic/gohugo-theme-ananke#473]
Noticed that the site-header.html partial's featured image logic is different than the home page and the page-header.html partial. This should call the GetFeaturedImage partial so that the behavior is consistent.

**Comment by py20555sti** [comment]
This still seems to be the case. Notice how the size of the feature image differs across:
* https://ananke-theme.netlify.app/about/
* https://ananke-theme.netlify.app/post/

It would appear that it's only the `post` that suffers from a smaller image.
I think it's caused by `{{ partial "page-header.html" . }}`.

FWIW having a custom layout for `layouts/posts/single.html` with:
```
{{ define "header" }}
{{ end }}
```

sets the correct size, but that would require a fully fledge snippet, including the body, which seems wasteful.
