### ISSUE TITLE
Is it possible to add images inline and resize using markdown?

### ISSUE THREAD

**Issue by matt-sharp** [theNewDynamic/gohugo-theme-ananke#508]
When I add an image using markdown it gets auto-resized and is too large, here's the syntax I'm using

`![image](https://www.url.com/img/image.jpg)`

I've tried using a combination of markdown and Html as mentioned [here ](https://stackoverflow.com/questions/24383700/resize-image-in-the-wiki-of-github-using-markdown/55131726) but this doesn't work.

**Comment by regisphilibert** [comment]
Hi @matt-sharp. 

I don't think the syntax mentioned in the provided link is supported yet by Hugo and Goldmark (its default markdown renderer) **but** since Hugo 0.81.0, Goldmark  supports markdown attribute which allow to add classes to blocks in your md. This will not work on image (which are not blocks), but on its parent paragraph though.

```mardkown
![image](https://www.url.com/img/image.jpg)
{.something}
```
👇 
```html
<p class="something">
  <img src="https://www.url.com/img/image.jpg" alt="image">
</p>
```
This should allow you to constrain images using CSS.

You will need to allow block attributes through the markup setting:
```yaml
# config.yaml
markup:
  goldmark:
    parser:
      attribute:
        block: true
```

Adding custom attributes to blocks is supported but to a point (prefixed with `data-`)

```markdown
Magnis dis parturient montes, nascetur ridiculus mus.
{data-something="test"}
```

**Comment by nedjo** [comment]
You could also look at using an [image markdown render hook](https://gohugo.io/templates/render-hooks/#image-markdown-example).

**Comment by jmooring** [comment]
This can be closed. 

#### Option 1 (easy): Use Markdown attributes

<https://gohugo.io/content-management/markdown-attributes/>

site configuration

```text
[markup.goldmark.parser.attribute]
block = true
title = true

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
```

markdown 

```text
![alt](/images/a.jpg)
{style="width: 300px; height: auto"}

or

![alt](/images/a.jpg)
{class="foo"}

or

![alt](/images/a.jpg)
{.foo}

```

#### Option 2 (not easy): Create a image render hook

<https://gohugo.io/render-hooks/images/>

Start with Hugo's [embedded image render hook](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/_markup/render-image.html), then modify it to read key-value pairs from the destination query string, passing them to the relevant [image processing method](https://gohugo.io/content-management/image-processing/#image-processing-methods). 

Your markdown might look something like this:

```text
![alt](/images/a.jpg?width=300&height=auto)
```
