### ISSUE TITLE
Changing Twitter social logo to X

### ISSUE THREAD

**Issue by melroy89** [theNewDynamic/gohugo-theme-ananke#653]
Twitter has changed the name and logo to "X".. This was not my idea.. but you might want to change the bird to X.

**Comment by smw355** [comment]
any update on this?

**Comment by melroy89** [comment]
Nope

**Comment by davidsneighbour** [comment]
For now your option is to replace the files in your repository root to override the theme files. Put the new logo into `assets/ananke/socials/twitter.svg` in your repository root (NOT the theme folder). This will override the theme icon.

In the long term, I am working on changing how social media networks are configured so that users can define labels/icons themselves. Until then, override the theme files.

**Comment by melroy89** [comment]
@davidsneighbour  You also removed the RSS icon in this commit: https://github.com/theNewDynamic/gohugo-theme-ananke/commit/c672ad429938bd8370cb906d3f9c2878a3b773be?

**Comment by davidsneighbour** [comment]
That came from rss and mail/envelope not being part of the fontawesome brands set. I'll re-add this of course (or already did, I remember having touched that config.

**Comment by melroy89** [comment]
> That came from rss and mail/envelope not being part of the fontawesome brands set. I'll re-add this of course (or already did, I remember having touched that config. Those two icons are manually added.

It wasn't added back.
