### ISSUE TITLE
bug: Getting started - The config file instructions do not seem to be correct

### ISSUE THREAD

**Issue by cchessnz** [theNewDynamic/gohugo-theme-ananke#730]
Following the instructions at https://github.com/theNewDynamic/gohugo-theme-ananke  README for getting started with the theme and example site, the behaviour is not as expected; and the instructions included an invalid step.

## Expected Behavior
After following the instructions under "Getting started", I'm expecting the front page to look similar to that at https://gohugo-theme-ananke.pages.dev/  (without the recent articles).

## Current Behavior
The front page ( http://localhost:1313/ ) shows a black area with title "My New Hugo Site"

## Possible Solution
Not sure, I am new to Hugo and picked the Ananke theme as it looked attractive and there was a tutorial. I am guessing the instructions are out of date with respect to the latest version of Hugo, and the actual content of the current `config.toml` file.

## Steps to Reproduce
1. hugo new site testsite
2. cd testsite
3. git init
4. git submodule https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke  (NOTE: I didn't install "go" as that was only mentioned under the Hugo Module installation method, which I didn't use)
5. cp themes/ananke/exampleSite/config.toml .
6. The instructions say "You may need to delete the line: `themesDir = "../.."`"  , but there was no such line.
7. Add the line `themes = 'ananke'` to the end of the default `hugo.toml`   (This step was not in the README, see below)
8. hugo server

## Context (Environment)
I am trying to use the Example Site as a starting point, and add my own customizations from there.

## Detailed Description
It seems that the `config.toml` file in the project's root directory is ignored entirely -- if I rename the file to something random, there are no changes in behaviour.  I am using hugo v0.135.0 in Ubuntu on WSL2.

The step 7 in my list above, was not in the Ananke README, but omitting this step causes the home page to just give `Page Not Found`.  The instruction to add `themes = 'ananke'` was given at https://gohugo.io/getting-started/quick-start/ .

**Comment by FiableDotBiz** [comment]
Moreover, depending on whom this theme is designed to, the installation instructions (https://themes.gohugo.io/themes/gohugo-theme-ananke/) are fully understandable, or not. I'm a beginner in Hugo, and there are things I don't or didn't understand.

- First of all, on the above mentioned page there is a "Download" button but clicking it doesn't download anything. It should be explained what to do next.
- Then it's written "hugo mod init github.com/<your_user>/<your_project>" but what on earth is "your_user"? I guess "your_project" means "the name of the website you want to build".
-  It's also written "Add the theme’s repo to your config.toml:
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]"
What is this for, since this line is already in "ExampleSite/config.toml" and the instructions says later "You’ll find a file called config.toml. To use it, copy the config.toml in the root folder of your Hugo site."
-  "To enable comments, add following to your config file:
    DISQUS:
    [services.disqus]
      shortname = 'YOURSHORTNAME'
    COMMENTO:
   (...)"
What do "DISQUS" and "COMMENTO" mean? Are they alternatives? What is "YOURSHORTNAME"?
- 'You may need to delete the line: themesDir = "../.."' : there is no such line in your config.toml file.

**Comment by davidsneighbour** [comment]
@cchessnz please test if with the latest changes in main you still get the empty black page. I fixed some things recently, but not specifically due to your issue. Right now I can install without issues. 

You are right, the `themesDir` seems not to be required anymore. 

I will work through both quick start guides and fix the last little issues today and release v2.11.0 later today. Keep an eye on it. 

@FiableDotBiz some of these concerns have already been fixed, others are common sense issues (like username and reponame in an github URL). I recently wrote [a quick intro to Hugo Modules](https://kollitsch.dev/blog/2024/howto-use-gohugo-modules/) and will link to that. Other than that I will ignore new issues in comments to existing issues. It's getting quite confusing and mostly unrelated this way. Individual support requests have to go into [Discussions](https://github.com/theNewDynamic/gohugo-theme-ananke/discussions).
