### ISSUE TITLE
HUGO_ENVIRONMENT env variable is not respected, only outdated HUGO_ENV is.

### ISSUE THREAD

**Issue by davidsneighbour** [theNewDynamic/gohugo-theme-ananke#733]
HUGO_ENVIRONMENT env variable is not respected, only outdated HUGO_ENV is.

_Originally posted by @bubenkoff in https://github.com/theNewDynamic/gohugo-theme-ananke/issues/201#issuecomment-2408885569_

**Comment by jmooring** [comment]
`getenv "HUGO_ENV"` is used throughout the code base (5 instances). Not sure why we're using an OS template function instead of one of these: [`hugo.Environment`](https://gohugo.io/functions/hugo/environment/), [`hugo.IsDevelopment`](https://gohugo.io/functions/hugo/isdevelopment/), [`hugo.IsProduction`](https://gohugo.io/functions/hugo/isproduction/), or [`hugo.IsServer`](https://gohugo.io/functions/hugo/isserver/).

Perhaps we kept the using `os.GetEnv` for backwards compatibility, but that's no longer relevant due to the minimum version specified here:
<https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/config/_default/hugo.toml#L1-L2>

**Comment by davidsneighbour** [comment]
Also, the reasoning behind this was probably to disable robots.txt on dev-environments only, which can be done now by having a `hugo.toml` in a different environment config than `production`. I might remove that completely and document it accordingly.
